description: >-
  Reference times are against twice the time of rsync on the same data,
  on the same machine.
state: /home/liw/benchmark/state.yaml
git: /home/liw/obnam/obnam
obnam_config:
  repository-format: green-albatross
benchmarks:
  - name: many_files
    description: backup many small files
    steps:
      - live: genbackupdata . --create=100Ki --file-size=1 --quiet
        label: generate_data
        include_in_total: False
      - obnam: backup
        reference: 112
        include_in_total: True
      - obnam: restore
        reference: 112
        include_in_total: True
      - obnam: backup
        include_in_total: True
  - name: one_big_file
    description: backup one big file
    steps:
      - live: genbackupdata . --create=1G --file-size=999999T
        label: generate_data
        include_in_total: False
      - obnam: backup
        reference: 42
        include_in_total: True
      - obnam: restore
        reference: 42
        include_in_total: True
reports_dir: /home/liw/benchmark/reports
html_dir: /home/liw/benchmark/html
